### ISSUE TITLE
LGPL, MPL  and iOS / Xamarin distributions

### ISSUE THREAD

**Issue by hinterlandsupplyco** [mono/taglib-sharp#148] opened 2019-02-22 04:02 UTC
LGPL is notoriously fuzzy on iOS distribution because AppStore apps can’t be dynamically linked. The original taglib was released under LGPL and Mozilla Public License. Is is possible to have taglib-sharp also released under both licenses?

**Comment by hinterlandsupplyco** [comment] 2019-02-22 04:26
Looking at Q11, Q12 and Q14 of the Mozilla Public License it appears you should/could already be licensing taglib-sharp as MPL and LGPL and a simple Readme.md update and file header should suffice. 

The original taglib had the LGPL header along with the following MPL addendum:

Alternatively, this file is available under the Mozilla Public License Version 1.1.  You may obtain a copy of the License at http://www.mozilla.org/MPL/  


Source: https://www.mozilla.org/en-US/MPL/2.0/FAQ/
Source: https://github.com/taglib/taglib

**Comment by decriptor** [comment] 2019-02-22 05:42
Duplicate of #114

**Closed by decriptor** 2019-02-22 05:42 UTC
